name: fisheye_gs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - plyfile
  - python=3.8
  - pip
  - pytorch
  - torchaudio
  - torchvision
  - tqdm
  - pip:
    - submodules/fisheye_gs_rasterizer
    - submodules/simple-knn