name: fisheye_gs
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.8
  - plyfile
  - tqdm
  - pip:
    - submodules/fisheye_gs_rasterizer
    - submodules/simple-knn